biblio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from contact.views import MessageAddView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^shelf/', include('shelf.urls', namespace='shelf') ),
    url(r'^contact/$', MessageAddView.as_view()),
]

shelf/urls.py
from django.conf.urls import include, url

from shelf.views import (AuthorListView, AuthorDetailView, BookListView, BookDetailView)

urlpatterns = [
    url(r'^autorzy/$', AuthorListView.as_view(), name='author-list'),
    url(r'^autorzy/(?P<pk>\d+)/$', AuthorDetailView.as_view(), name='author-detail'),
    url(r'^ksiazki/$', BookListView.as_view(), name='book-list'),
    url(r'^ksiazki/(?P<pk>\d+)$', BookDetailView.as_view(), name='book-detail'),
]

contact/forms.py
from django import forms
from .models import Message

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('name', 'email', 'message')


class ContactForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea())

    def clean_name(self):
        data = self.cleaned_data['name']
        if "D" not in data:
            raise forms.ValidationError("Musisz mieć imię zawierająće 'D'!")
        return data

contact/views.py
from django.views.generic import DetailView, FormView
from .models import Message
from .forms import MessageForm, ContactForm

#class MessageDetailView(DetailView):
#    model = Message

class MessageAddView(FormView):
    form_class = ContactForm
    template_name = 'contact/message_form.html'
    success_url = '/'

    #def form_valid(self, form):
     #   form.save() #bo form jest instancją modelform który posiada metodą
      #  return super (MessageAddView, self).form_valid(form)

contact/templates/contact/message_form.html
{% extends "base.html"%}

{% block 'content' %}
<form method="post">
{% csrf_token %}
    <table>
        {{ form.as_table}}
    </table>
    <button type="submit">Wyślij</button>
</form>

{% endblock %}

shelf/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>blas</title>
</head>
<body>
    {% block 'content' %}



    {% endblock %}
</body>
</html>

shelf/templates/shelf/author_detail.html
{%  extends "base.html" %}

{% block 'content' %}
<div><a href="{%  url 'shelf:author-list'%}"> Powrót do listy autorów</a> </div>

   Profil autora: {{ object.last_name }}, {{ object.first_name }}

<h2> Książki</h2>
<ul>
    {% for book in object.book_set.all %}
        <li>
            <a href="{% url 'shelf:book-detail' book.id %}">{{ book.title }} -
        </li>
    {% endfor %}
</ul>
{% endblock %}

shelf/templates/shelf/author_list.html
{%  extends "base.html" %}
<ul>
{% block 'content' %}
    {% for author in object_list %}
       <li><a href="{% url 'shelf:author-detail' author.id %}">{{author.first_name }}{{ author.last_name }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

shelf/templates/shelf/book_detail.html
{% extends "base.html" %}

{% block 'content' %}
<a href = "{% url 'shelf:book-list' %} "> Powrót do listy książek</a>
 <h1>{{ object.title }}</h1>


{% endblock %}

shelf/templates/shelf/book_list.html
{% extends "base.html" %}

{% block 'content' %}
<ul>
{% for book in object_list %}
    <li><a href="{% url 'shelf:book-detail' book.id %}">{{ book.title }} -
        {% for author in book.authors.all %}
            {{ authot.first_name }} {{  author.last_name }}
            {% if not forloop  %}, {% endif %}
        {% endfor %}
    </li>
{% endfor %}
</ul>


{% endblock %}